pub use crate::readers::branch_table::{BranchReaderError, BranchTableReader};
pub use crate::readers::code_section::{CodeReaderError, CodeSectionReader};
pub use crate::readers::custom_section::{CustomReaderError, CustomSectionReader};
pub use crate::readers::data_section::{DataReaderError, DataSectionReader};
pub use crate::readers::element_section::{ElementReaderError, ElementSectionReader};
pub use crate::readers::export_section::{ExportReaderError, ExportSectionReader};
pub use crate::readers::function_section::{FunctionReaderError, FunctionSectionReader};
pub use crate::readers::global_section::{GlobalReaderError, GlobalSectionReader};
pub use crate::readers::import_section::{ImportReaderError, ImportSectionReader};
pub use crate::readers::instruction::{InstructionReader, InstructionReaderError};
pub use crate::readers::memory_section::{MemoryReaderError, MemorySectionReader};
pub use crate::readers::start_section::{StartReaderError, StartSectionReader};
pub use crate::readers::table_section::{TableReaderError, TableSectionReader};
pub use crate::readers::type_section::{TypeReaderError, TypeSectionReader};

mod custom_section;
mod type_section;
mod import_section;
mod function_section;
mod table_section;
mod memory_section;
mod global_section;
mod export_section;
mod start_section;
mod element_section;
mod code_section;
mod data_section;
mod branch_table;
mod instruction;
pub mod binary;
