pub use crate::readers::custom_section::{CustomSectionReader, CustomReaderError};
pub use crate::readers::type_section::{TypeSectionReader, TypeReaderError};
pub use crate::readers::import_section::{ImportSectionReader, ImportReaderError};
pub use crate::readers::function_section::{FunctionSectionReader, FunctionReaderError};
pub use crate::readers::table_section::{TableSectionReader, TableReaderError};
pub use crate::readers::memory_section::{MemorySectionReader, MemoryReaderError};
pub use crate::readers::global_section::{GlobalSectionReader, GlobalReaderError};
pub use crate::readers::export_section::{ExportSectionReader, ExportReaderError};
pub use crate::readers::start_section::{StartSectionReader, StartReaderError};
pub use crate::readers::element_section::{ElementSectionReader, ElementReaderError};
pub use crate::readers::data_section::{DataSectionReader, DataReaderError};

mod custom_section;
mod type_section;
mod import_section;
mod function_section;
mod table_section;
mod memory_section;
mod global_section;
mod export_section;
mod start_section;
mod element_section;
mod data_section;
